/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * e.g. "home" for landing page, "about-us", etc.
   */
  slug: string;
  headerVariant?: ('transparent' | 'solid-green' | 'solid-white' | 'hidden') | null;
  layout?:
    | (
        | {
            badge?: string | null;
            heading: string;
            backgroundImage: number | Media;
            primaryButtonText?: string | null;
            primaryButtonUrl?: string | null;
            secondaryButtonText?: string | null;
            secondaryButtonUrl?: string | null;
            /**
             * Link to YouTube, Vimeo, or video modal
             */
            videoUrl?: string | null;
            stats?:
              | {
                  icon?: ('book' | 'students' | 'teacher' | 'trophy') | null;
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            badge?: string | null;
            heading: string;
            description?: string | null;
            buttonText?: string | null;
            buttonUrl?: string | null;
            imageOne?: (number | null) | Media;
            imageTwo?: (number | null) | Media;
            floatingBadgeIcon?: (number | null) | Media;
            floatingBadgeLine1?: string | null;
            floatingBadgeLine2?: string | null;
            stat1Value?: string | null;
            stat1Label?: string | null;
            stat1Icon?: (number | null) | Media;
            stat2Value?: string | null;
            stat2Label?: string | null;
            stat2Icon?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutUs';
          }
        | {
            badge?: string | null;
            heading: string;
            description?: string | null;
            buttonText?: string | null;
            buttonUrl?: string | null;
            imageOne?: (number | null) | Media;
            imageTwo?: (number | null) | Media;
            backgroundImage?: (number | null) | Media;
            bannerText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programs';
          }
        | {
            badge?: string | null;
            heading: string;
            description?: string | null;
            tabs?:
              | {
                  tabName: string;
                  images?:
                    | {
                        image: number | Media;
                        caption?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'facilities';
          }
        | {
            badge?: string | null;
            heading: string;
            academicYears?:
              | {
                  year: string;
                  rankHolders?:
                    | {
                        studentName: string;
                        rank: string;
                        score: string;
                        standard?: string | null;
                        photo?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'toppers';
          }
        | {
            badge?: string | null;
            heading: string;
            viewMoreText?: string | null;
            viewMoreLink?: string | null;
            galleryImages?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            ctaBar?: {
              showCtaBar?: boolean | null;
              tagline?: string | null;
              heading?: string | null;
              studentImage?: (number | null) | Media;
              buttonText?: string | null;
              buttonUrl?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'campusLife';
          }
        | {
            badge?: string | null;
            heading: string;
            testimonials?:
              | {
                  cardStyle?: ('green' | 'yellow') | null;
                  rating?: number | null;
                  quote: string;
                  authorName: string;
                  authorRole: string;
                  authorPhoto?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            badge?: string | null;
            heading: string;
            exploreMoreText?: string | null;
            viewAllUrl?: string | null;
            items?:
              | {
                  date: string;
                  title: string;
                  image?: (number | null) | Media;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsEvents';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  headerVariant?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              badge?: T;
              heading?: T;
              backgroundImage?: T;
              primaryButtonText?: T;
              primaryButtonUrl?: T;
              secondaryButtonText?: T;
              secondaryButtonUrl?: T;
              videoUrl?: T;
              stats?:
                | T
                | {
                    icon?: T;
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutUs?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              imageOne?: T;
              imageTwo?: T;
              floatingBadgeIcon?: T;
              floatingBadgeLine1?: T;
              floatingBadgeLine2?: T;
              stat1Value?: T;
              stat1Label?: T;
              stat1Icon?: T;
              stat2Value?: T;
              stat2Label?: T;
              stat2Icon?: T;
              id?: T;
              blockName?: T;
            };
        programs?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              imageOne?: T;
              imageTwo?: T;
              backgroundImage?: T;
              bannerText?: T;
              id?: T;
              blockName?: T;
            };
        facilities?:
          | T
          | {
              badge?: T;
              heading?: T;
              description?: T;
              tabs?:
                | T
                | {
                    tabName?: T;
                    images?:
                      | T
                      | {
                          image?: T;
                          caption?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        toppers?:
          | T
          | {
              badge?: T;
              heading?: T;
              academicYears?:
                | T
                | {
                    year?: T;
                    rankHolders?:
                      | T
                      | {
                          studentName?: T;
                          rank?: T;
                          score?: T;
                          standard?: T;
                          photo?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        campusLife?:
          | T
          | {
              badge?: T;
              heading?: T;
              viewMoreText?: T;
              viewMoreLink?: T;
              galleryImages?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              ctaBar?:
                | T
                | {
                    showCtaBar?: T;
                    tagline?: T;
                    heading?: T;
                    studentImage?: T;
                    buttonText?: T;
                    buttonUrl?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              badge?: T;
              heading?: T;
              testimonials?:
                | T
                | {
                    cardStyle?: T;
                    rating?: T;
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    authorPhoto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsEvents?:
          | T
          | {
              badge?: T;
              heading?: T;
              exploreMoreText?: T;
              viewAllUrl?: T;
              items?:
                | T
                | {
                    date?: T;
                    title?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  topBar?: {
    showTopBar?: boolean | null;
    phone?: string | null;
    email?: string | null;
  };
  logo?: (number | null) | Media;
  navItems?:
    | {
        label: string;
        link: string;
        isActive?: boolean | null;
        /**
         * Option to display the (v) expand arrow icon next to this menu item
         */
        showExpandIcon?: boolean | null;
        hasDropdown?: boolean | null;
        subItems?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  ctaBanner: {
    showCtaBanner?: boolean | null;
    tagline?: string | null;
    heading: string;
    description?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  logo?: (number | null) | Media;
  description?: string | null;
  contactInfo?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  quickLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'twitter' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  topBar?:
    | T
    | {
        showTopBar?: T;
        phone?: T;
        email?: T;
      };
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        isActive?: T;
        showExpandIcon?: T;
        hasDropdown?: T;
        subItems?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  ctaBanner?:
    | T
    | {
        showCtaBanner?: T;
        tagline?: T;
        heading?: T;
        description?: T;
        buttonText?: T;
        buttonUrl?: T;
        backgroundImage?: T;
      };
  logo?: T;
  description?: T;
  contactInfo?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  quickLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}